@JWT_Authentication_HostAddress = https://localhost:7028

GET {{JWT_Authentication_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{JWT_Authentication_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###
